name: CI/CD Pipeline - VM Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Build da API
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build API Docker Image
        run: docker build -t jgneves/eagletechapi:${{ github.sha }} ./eagletechapi

      # Build do Client
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Build Client Docker Image
        run: |
          docker build \
          -t jgneves/eagletechclient:${{ github.sha }} \
          --build-arg REACT_APP_GEMINI_KEY=${{ secrets.REACT_APP_GEMINI_KEY }} \
          ./eagletechclient

        # run: docker build -t jgneves/eagletechclient:${{ github.sha }} ./eagletechclient

      # Login no Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Verify Docker login
        run: |
          echo "Verificando docker info (sem expor secrets)"
          docker info --format '{{json .RegistryConfig}}' || true

      # Tag e Push
      - name: Push Images to Docker Hub
        run: |
          docker tag jgneves/eagletechapi:${{ github.sha }} jgneves/eagletechapi:latest
          docker push jgneves/eagletechapi:${{ github.sha }}
          docker push jgneves/eagletechapi:latest

          docker tag jgneves/eagletechclient:${{ github.sha }} jgneves/eagletechclient:latest
          docker push jgneves/eagletechclient:${{ github.sha }}
          docker push jgneves/eagletechclient:latest

      # Deploy remoto na VM via SSH
      - name: Deploy on Remote VM
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: 7642
          script: |
            docker compose pull
            docker compose up -d --remove-orphans
            docker system prune -f
